<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>DataWeave</string>
    <key>scopeName</key>
    <string>source.data-weave</string>
    <key>fileTypes</key>
    <array>
      <string>dwl</string>
    </array>
    <key>uuid</key>
    <string>ba6390ae-c50f-4dce-97f1-951dab8fc607</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#namespace</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#document</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#constant</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keyword</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#directive</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#identifier</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#selector</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>namespace</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(ns)\s+([[:alpha:]][[:alnum:]_]*)\s+([^\s]*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.dw</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.variable.dw</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>markup.underline.link</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.block.dw</string>
            <key>begin</key>
            <string>/\*</string>
            <key>end</key>
            <string>\*/</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\s*((//).*$\n?)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>comment.line.double-slash.dw</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.dw</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>document</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.operator.body-marker.dw</string>
            <key>match</key>
            <string>(---)</string>
          </dict>
        </array>
      </dict>
      <key>constant</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#regex</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string-constants</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#number-constants</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.language.dw</string>
            <key>match</key>
            <string>(?&lt;![[:alnum:]])(?:true|false|null)(?![[:alnum:]_])</string>
          </dict>
        </array>
      </dict>
      <key>keyword</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.control.dw</string>
            <key>match</key>
            <string>(?&lt;![[:alnum:]])(?:if|else|unless|do|using|default|match|case|update)(?![[:alnum:]_])</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.dw</string>
            <key>match</key>
            <string>(?&lt;![[:alnum:]_])(?:and|or|not|as|is)(?![[:alnum:]_])</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.case.dw</string>
            <key>match</key>
            <string>(-&gt;)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.metadata.dw</string>
            <key>match</key>
            <string>(&lt;~)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.comparison.dw</string>
            <key>match</key>
            <string>(~=|==|!=|!=|&lt;=|&gt;=|&lt;|&gt;)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.dw</string>
            <key>match</key>
            <string>(=)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.declaration.dw</string>
            <key>match</key>
            <string>(:)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.arithmetic.dw</string>
            <key>match</key>
            <string>(\-|\+|\*|\/)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.implement.dw</string>
            <key>match</key>
            <string>\?\?\?</string>
          </dict>
        </array>
      </dict>
      <key>directive</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.directive.version.dw</string>
            <key>begin</key>
            <string>(%dw)\s+([0-9]+\.[0-9]+)(?!\$|\.)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.directive.version.dw</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.version.dw</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\n)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>storage.type.dw</string>
            <key>match</key>
            <string>(?&lt;![[:alnum:]_])(?:import|fun|ns|input|var|type|annotation|output|from)(?![[:alnum:]_])</string>
          </dict>
        </array>
      </dict>
      <key>identifier</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>entity.name.variable.dw</string>
            <key>match</key>
            <string>[[:alpha:]][[:alnum:]_]*</string>
          </dict>
        </array>
      </dict>
      <key>selector</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>storage.type.dw</string>
            <key>match</key>
            <string>\.\.|\.\*|\.\^|\.\@|\.</string>
          </dict>
          <dict>
            <key>name</key>
            <string>storage.type.dw</string>
            <key>begin</key>
            <string>\[</string>
            <key>end</key>
            <string>\]</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>regex</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>string.regexp.dw</string>
            <key>match</key>
            <string>\/.*\/</string>
          </dict>
        </array>
      </dict>
      <key>string-constants</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>string.quoted.double.dw</string>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.dw</string>
              </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.dw</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string-interpolation</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>string.quoted.single.dw</string>
            <key>begin</key>
            <string>'</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.dw</string>
              </dict>
            </dict>
            <key>end</key>
            <string>'</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.dw</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string-interpolation</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>string.quoted.backtick.dw</string>
            <key>begin</key>
            <string>`</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.dw</string>
              </dict>
            </dict>
            <key>end</key>
            <string>`</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.dw</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string-interpolation</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>string-interpolation</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\$\(</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.other.dw</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.other.dw</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#selector</string>
              </dict>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>(\$)([[:alpha:]][[:alnum:]_]*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.dw</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.variable.dw</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>number-constants</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.numeric.dw</string>
            <key>match</key>
            <string>(?:0|[1-9][0-9]*)(?:\.[0-9]+)?(?:[eE][0-9]*)?</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>